plugins {
    id 'com.android.application'
}

android {
    namespace 'com.plugin.sdk.demo'
    compileSdk 37

    defaultConfig {
        applicationId "com.plugin.sdk.demo"
        minSdk 21
        targetSdk 37
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

}

dependencies {
    implementation project(':sdk')
}

// 不可删除：运行 demo 时自动触发插件编译（对齐 360 sdk_social_pay_demo_online/build.gradle L68）
// 运行 ./gradlew :demo:assembleDebug 时，自动先编译插件并把插件 APK 复制到 demo assets
tasks.configureEach {
    task ->
        // 一定要这么写，否则会触发编译的递归
        if (task.name == "assembleDebug" && project.name == "demo") {
            // 只有真正运行 demo 产出 APK 时才会有值，点击 Sync 则返回空数组 []
            def runTasks = gradle.startParameter.taskNames
            if (":demo:assembleDebug" in runTasks) {
                def isWindows = org.gradle.internal.os.OperatingSystem.current().isWindows()
                def gradlew = isWindows
                        ? new File(rootDir, "gradlew.bat").absolutePath
                        : new File(rootDir, "gradlew").absolutePath
                project.services.get(ExecOperations).exec {
                    workingDir rootDir
                    commandLine gradlew, ":plugin:assembleRelease"
                }
            }
        }
}